/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD_entidadesPrincipales;

import Modelo.Dueño;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Tous
 */
public class vistaDueño extends javax.swing.JFrame {

    /**
     * Creates new form VistaDueño
     */
    public vistaDueño() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        creartabla();
        cargarTabla();
        Atras.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        panelOperaciones = new java.awt.Panel();
        nombre = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        codigoPostal = new javax.swing.JTextField();
        Añadir = new javax.swing.JButton();
        identificacion = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        Borrar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Atras = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        apellido = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        jRadioButtonMas = new javax.swing.JRadioButton();
        jRadioButtonFem = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dueño");

        panelOperaciones.setBackground(new java.awt.Color(14, 15, 34));
        panelOperaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nombre.setBackground(new java.awt.Color(184, 185, 194));
        nombre.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        telefono.setBackground(new java.awt.Color(184, 185, 194));
        telefono.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });

        codigoPostal.setBackground(new java.awt.Color(184, 185, 194));
        codigoPostal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        codigoPostal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigoPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoPostalKeyTyped(evt);
            }
        });

        Añadir.setBackground(new java.awt.Color(184, 185, 194));
        Añadir.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Añadir.setText("AÑADIR");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        identificacion.setBackground(new java.awt.Color(184, 185, 194));
        identificacion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        identificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                identificacionKeyTyped(evt);
            }
        });

        email.setBackground(new java.awt.Color(184, 185, 194));
        email.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("NOMBRE");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("APELLIDO");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("TELEFONO");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("EMAIL");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("CODIGO POSTAL");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SEXO");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("IDENTIFICACIÓN");

        jScrollPane1.setBackground(new java.awt.Color(14, 15, 34));

        jTable.setBackground(new java.awt.Color(184, 185, 194));
        jTable.setModel(tabla);
        jTable.setSelectionBackground(new java.awt.Color(55, 175, 177));
        jTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable);

        Borrar.setBackground(new java.awt.Color(184, 185, 194));
        Borrar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Borrar.setText("BORRAR");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        Consultar.setBackground(new java.awt.Color(184, 185, 194));
        Consultar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Consultar.setText("CONSULTAR");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(184, 185, 194));
        Modificar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 255, 204));

        Atras.setBackground(new java.awt.Color(184, 185, 194));
        Atras.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Atras.setText("ATRAS");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 255, 204));

        apellido.setBackground(new java.awt.Color(184, 185, 194));
        apellido.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Guardar.setBackground(new java.awt.Color(184, 185, 194));
        Guardar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jRadioButtonMas.setBackground(new java.awt.Color(14, 15, 34));
        buttonGroupSexo.add(jRadioButtonMas);
        jRadioButtonMas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButtonMas.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMas.setText("Masculino");
        jRadioButtonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonMasMouseClicked(evt);
            }
        });

        jRadioButtonFem.setBackground(new java.awt.Color(14, 15, 34));
        buttonGroupSexo.add(jRadioButtonFem);
        jRadioButtonFem.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButtonFem.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFem.setText("Femenino");
        jRadioButtonFem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelOperacionesLayout = new javax.swing.GroupLayout(panelOperaciones);
        panelOperaciones.setLayout(panelOperacionesLayout);
        panelOperacionesLayout.setHorizontalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel7)
                                .addGap(137, 137, 137)
                                .addComponent(jLabel1))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(140, 140, 140)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(312, 312, 312))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(319, 319, 319))))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(Consultar)
                        .addGap(61, 61, 61)
                        .addComponent(Modificar)
                        .addGap(59, 59, 59)
                        .addComponent(Borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Atras))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(73, 73, 73))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(156, 156, 156))
                                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                                        .addGap(92, 92, 92)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87)
                                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButtonMas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonFem)))))
                        .addGap(51, 51, 51)))
                .addGap(40, 40, 40))
        );
        panelOperacionesLayout.setVerticalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonMas)
                    .addComponent(jRadioButtonFem))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        btnAñadir();
    }//GEN-LAST:event_AñadirActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        btnConsultar();
    }//GEN-LAST:event_ConsultarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        btnActualizar();
    }//GEN-LAST:event_ModificarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        btnEliminar();
    }//GEN-LAST:event_BorrarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        btnAtras();
    }//GEN-LAST:event_AtrasActionPerformed

    private void codigoPostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoPostalKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (codigoPostal.getText().length() >= 6) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_codigoPostalKeyTyped

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (telefono.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        btnGuardar();
    }//GEN-LAST:event_GuardarActionPerformed

    private void identificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identificacionKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (identificacion.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_identificacionKeyTyped

    private void jRadioButtonMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonMasMouseClicked
        sexo();
    }//GEN-LAST:event_jRadioButtonMasMouseClicked

    private void jRadioButtonFemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFemMouseClicked
        sexo();
    }//GEN-LAST:event_jRadioButtonFemMouseClicked

    DefaultTableModel tabla = new DefaultTableModel();

    public void creartabla() {
        tabla.addColumn("IDENTIFICACION");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("APELLIDO");
        tabla.addColumn("TELEFONO");
    }

    public void llenartabla() {
        tabla.setNumRows(0);
        for (Dueño d : vistaInicial.ctrldueño.getDueños()) {
            String[] fila = {d.getIdentificacion(), d.getNombre().toUpperCase(), d.getApellido().toUpperCase(), d.getTelefono()};
            tabla.addRow(fila);
        }
    }

    public void cargarTabla() {
        if (vistaInicial.ctrldueño.validarArchivo() == true) {
            tabla.setNumRows(0);
            for (Dueño d : vistaInicial.ctrldueño.cargarDueños()) {
                String[] fila = {d.getIdentificacion(), d.getNombre().toUpperCase(), d.getApellido().toUpperCase(), d.getTelefono()};
                tabla.addRow(fila);
                vistaInicial.ctrldueño.agregar(d);
            }
        }
    }

    public void mostrarConsulta() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
        }
        tabla.setNumRows(0);
        for (Dueño d : vistaInicial.ctrldueño.getDueños()) {
            if (d.getIdentificacion().equals(identificacion.getText())) {
                String[] fila = {d.getIdentificacion(), d.getNombre().toUpperCase(), d.getApellido().toUpperCase(), d.getTelefono()};
                tabla.addRow(fila);
                nombre.setText(d.getNombre());
                apellido.setText(d.getApellido());
                codigoPostal.setText(d.getCodigoPostal());
                telefono.setText(d.getTelefono());
                email.setText(d.getEmail());
                nombre.setEnabled(true);
                apellido.setEnabled(true);
                jRadioButtonMas.setEnabled(true);
                jRadioButtonFem.setEnabled(true);
            }
        }
    }

    public void mostrarDueñoActualizar() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
        }
        tabla.setNumRows(0);
        for (Dueño d : vistaInicial.ctrldueño.getDueños()) {
            if (d.getIdentificacion().equals(identificacion.getText())) {
                String[] fila = {d.getIdentificacion(), d.getNombre().toUpperCase(), d.getApellido().toUpperCase(), d.getTelefono()};
                tabla.addRow(fila);
                nombre.setText(d.getNombre());
                apellido.setText(d.getApellido());
            }
        }
    }

    public void vaciar() {
        identificacion.setText("");
        nombre.setText("");
        apellido.setText("");
        codigoPostal.setText("");
        telefono.setText("");
        email.setText("");
        buttonGroupSexo.clearSelection();
        Atras.setVisible(false);
        Añadir.setEnabled(true);
        Guardar.setEnabled(true);
        Modificar.setEnabled(true);
        jRadioButtonMas.setEnabled(true);
        jRadioButtonFem.setEnabled(true);
    }

    public String sexo() {
        String validar = "";
        if (jRadioButtonMas.isSelected()) {
            validar = "MASCULINO";
        }
        if (jRadioButtonFem.isSelected()) {
            validar = "FEMENINO";
        }
        return validar;
    }

    public void btnAñadir() {
        if (identificacion.getText().equals("") || nombre.getText().equals("")
                || apellido.getText().equals("") || codigoPostal.getText().equals("")
                || telefono.getText().equals("") || email.getText().equals("")
                || sexo().equals("")) {
            JOptionPane.showMessageDialog(null, "¡FALTAN CAMPOS POR LLENAR!\n"
                    + "Por favor, complete todos los campos.", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (vistaInicial.ctrldueño.verificarYAgregar(identificacion.getText()) == true) {
                JOptionPane.showMessageDialog(null, "Hay una persona con la misma identidicación, digite la correcta por favor.",
                        "Agregar dueño", JOptionPane.ERROR_MESSAGE);
                identificacion.setText("");
            } else {
                if (identificacion.getText().length() != 10 || telefono.getText().length() != 10 || codigoPostal.getText().length() != 6) {
                    JOptionPane.showMessageDialog(null, "Por favor, ingrese los digitos que se requieren en el campo IDENTIFICACION, TELEFONO o CODIGO POSTAL.", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    Dueño constructor = new Dueño();
                    constructor.setIdentificacion(identificacion.getText());
                    constructor.setNombre(nombre.getText());
                    constructor.setApellido(apellido.getText());
                    constructor.setSexo(sexo());
                    constructor.setCodigoPostal(codigoPostal.getText());
                    constructor.setTelefono(telefono.getText());
                    constructor.setEmail(email.getText());
                    constructor.setEstado("ACTIVO");
                    constructor.setUsuario(constructor.getIdentificacion());
                    constructor.setContraseña(constructor.getIdentificacion());
                    vistaInicial.ctrldueño.agregar(constructor);
                    vaciar();
                    llenartabla();
                }
            }
        }
    }

    public void btnConsultar() {
        if (vistaInicial.ctrldueño.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "No se ha registrado ningun propietario.", "Consultar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion de la persona a buscar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                vistaInicial.ctrldueño.consultar(identificacion.getText());
                mostrarConsulta();
                Atras.setVisible(true);
                Añadir.setEnabled(false);
                Guardar.setEnabled(false);
                Modificar.setEnabled(false);
            }
        }
    }

    public void btnActualizar() {
        if (vistaInicial.ctrldueño.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "La lista se encuentra vacía.", "Actualizar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion de la persona a actualizar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                mostrarDueñoActualizar();
                nombre.setEnabled(false);
                apellido.setEnabled(false);
                jRadioButtonMas.setEnabled(false);
                jRadioButtonFem.setEnabled(false);
                if (codigoPostal.getText().equals("") || telefono.getText().equals("") || email.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos a actualizar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
                    Atras.setVisible(true);
                    Añadir.setEnabled(false);
                    Guardar.setEnabled(false);
                } else {
                    if (identificacion.getText().length() != 10 || telefono.getText().length() != 10 || codigoPostal.getText().length() != 6) {
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese los digitos que se requieren en el campo IDENTIFICACION, TELEFONO o CODIGO POSTAL.", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        vistaInicial.ctrldueño.actualizar(identificacion.getText(), codigoPostal.getText(), telefono.getText(), email.getText());
                        nombre.setEnabled(true);
                        apellido.setEnabled(true);
                        jRadioButtonMas.setEnabled(true);
                        jRadioButtonFem.setEnabled(true);
                        vaciar();
                        llenartabla();
                    }
                }
            }

        }
    }

    public void btnEliminar() {
        if (vistaInicial.ctrldueño.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "La lista se encuentra vacía.", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion de la persona a eliminar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                boolean validar = vistaInicial.ctrldueño.eliminar(identificacion.getText());
                if (validar == false) {
                    JOptionPane.showMessageDialog(null, "No existe alguna persona con esa identificación.", "Eliminar dueño", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    llenartabla();
                    vaciar();
                }
            }
        }
    }

    public void btnGuardar() {
        vistaInicial.ctrldueño.guardarDueño();
    }

    public void btnAtras() {
        nombre.setEnabled(true);
        apellido.setEnabled(true);
        jRadioButtonMas.setEnabled(true);
        jRadioButtonFem.setEnabled(true);
        llenartabla();
        vaciar();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaDueño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Añadir;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField apellido;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JTextField codigoPostal;
    private javax.swing.JTextField email;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButtonFem;
    private javax.swing.JRadioButton jRadioButtonMas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField nombre;
    public java.awt.Panel panelOperaciones;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
