/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD_entidadesPrincipales;

import Modelo.Conductor;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Tous
 */
public class vistaConductor extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame2
     */
    public vistaConductor() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        creartabla();
        cargarTabla();
        Atras.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        buttonGroupEDL = new javax.swing.ButtonGroup();
        panelOperaciones = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        Añadir = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        telefono = new javax.swing.JTextField();
        identificacion = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jlabel7 = new javax.swing.JLabel();
        nroLicencia = new javax.swing.JTextField();
        jlabel8 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jRadioButtonMas = new javax.swing.JRadioButton();
        jRadioButtonAct = new javax.swing.JRadioButton();
        jRadioButtonFem = new javax.swing.JRadioButton();
        jRadioButtonInact = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conductor");

        panelOperaciones.setBackground(new java.awt.Color(0, 255, 204));
        panelOperaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBackground(new java.awt.Color(14, 15, 34));

        jTable.setBackground(new java.awt.Color(184, 185, 194));
        jTable.setModel(tabla);
        jTable.setSelectionBackground(new java.awt.Color(55, 175, 177));
        jTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable);

        jlabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel1.setText("Nombre");

        jlabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel2.setText("Apellido");

        jlabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel3.setText("Identificacion");

        jlabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel5.setText("Telefono");

        jlabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel6.setText("Nro de licencia");

        Añadir.setBackground(new java.awt.Color(184, 185, 194));
        Añadir.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Añadir.setText("AÑADIR");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Consultar.setBackground(new java.awt.Color(184, 185, 194));
        Consultar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Consultar.setText("CONSULTAR");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(184, 185, 194));
        Modificar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Borrar.setBackground(new java.awt.Color(184, 185, 194));
        Borrar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Borrar.setText("BORRAR");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        telefono.setBackground(new java.awt.Color(184, 185, 194));
        telefono.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });

        identificacion.setBackground(new java.awt.Color(184, 185, 194));
        identificacion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        identificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                identificacionKeyTyped(evt);
            }
        });

        apellido.setBackground(new java.awt.Color(184, 185, 194));
        apellido.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nombre.setBackground(new java.awt.Color(184, 185, 194));
        nombre.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel7.setText("Estado de la licencia");

        nroLicencia.setBackground(new java.awt.Color(184, 185, 194));
        nroLicencia.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        nroLicencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nroLicencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nroLicenciaKeyTyped(evt);
            }
        });

        jlabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel8.setText("Sexo");

        Atras.setBackground(new java.awt.Color(184, 185, 194));
        Atras.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Atras.setText("ATRAS");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Guardar.setBackground(new java.awt.Color(184, 185, 194));
        Guardar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jRadioButtonMas.setBackground(new java.awt.Color(0, 255, 204));
        buttonGroupSexo.add(jRadioButtonMas);
        jRadioButtonMas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButtonMas.setText("Masculino");
        jRadioButtonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonMasMouseClicked(evt);
            }
        });

        jRadioButtonAct.setBackground(new java.awt.Color(0, 255, 204));
        buttonGroupEDL.add(jRadioButtonAct);
        jRadioButtonAct.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButtonAct.setText("Activa");
        jRadioButtonAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonActMouseClicked(evt);
            }
        });

        jRadioButtonFem.setBackground(new java.awt.Color(0, 255, 204));
        buttonGroupSexo.add(jRadioButtonFem);
        jRadioButtonFem.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButtonFem.setText("Femenino");
        jRadioButtonFem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFemMouseClicked(evt);
            }
        });

        jRadioButtonInact.setBackground(new java.awt.Color(0, 255, 204));
        buttonGroupEDL.add(jRadioButtonInact);
        jRadioButtonInact.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButtonInact.setText("Inactiva");
        jRadioButtonInact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonInactMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelOperacionesLayout = new javax.swing.GroupLayout(panelOperaciones);
        panelOperaciones.setLayout(panelOperacionesLayout);
        panelOperacionesLayout.setHorizontalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlabel1)
                                .addComponent(jlabel2))
                            .addComponent(jlabel3)
                            .addComponent(jlabel5)
                            .addComponent(jlabel6)
                            .addComponent(jlabel7)
                            .addComponent(jlabel8))
                        .addGap(26, 26, 26)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonMas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonFem))
                                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                                        .addComponent(jRadioButtonAct)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonInact)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Atras)
                                .addGap(18, 18, 18)
                                .addComponent(Borrar))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Modificar))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Consultar))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        panelOperacionesLayout.setVerticalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel1))
                        .addGap(17, 17, 17)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel2))
                        .addGap(26, 26, 26)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel6)
                            .addComponent(nroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel5)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel8)
                            .addComponent(jRadioButtonMas)
                            .addComponent(jRadioButtonFem))
                        .addGap(18, 18, 18)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel7)
                            .addComponent(jRadioButtonAct)
                            .addComponent(jRadioButtonInact))))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        btnAñadir();
    }//GEN-LAST:event_AñadirActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        btnConsultar();
    }//GEN-LAST:event_ConsultarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        btnActualizar();
    }//GEN-LAST:event_ModificarActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        btnEliminar();
    }//GEN-LAST:event_BorrarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        btnAtras();
    }//GEN-LAST:event_AtrasActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        btnGuardar();
    }//GEN-LAST:event_GuardarActionPerformed

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (telefono.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void nroLicenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nroLicenciaKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (nroLicencia.getText().length() >= 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_nroLicenciaKeyTyped

    private void identificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identificacionKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (identificacion.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_identificacionKeyTyped

    private void jRadioButtonMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonMasMouseClicked
        sexo();
    }//GEN-LAST:event_jRadioButtonMasMouseClicked

    private void jRadioButtonActMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonActMouseClicked
        estadoDeLicencia();
    }//GEN-LAST:event_jRadioButtonActMouseClicked

    private void jRadioButtonFemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFemMouseClicked
        sexo();
    }//GEN-LAST:event_jRadioButtonFemMouseClicked

    private void jRadioButtonInactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonInactMouseClicked
        estadoDeLicencia();
    }//GEN-LAST:event_jRadioButtonInactMouseClicked

    DefaultTableModel tabla = new DefaultTableModel();

    public void creartabla() {
        tabla.addColumn("IDENTIFICACION");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("APELLIDO");
        tabla.addColumn("TELEFONO");
        tabla.addColumn("NRO DE LIC.");
        tabla.addColumn("ESTADO DE LIC.");
    }

    public void llenartabla() {
        tabla.setNumRows(0);
        for (Conductor c : vistaInicial.ctrlconductor.getConductores()) {
            String[] fila = {c.getIdentificacion(), c.getNombre().toUpperCase(), c.getApellido().toUpperCase(), c.getTelefono(), c.getNroLicencia(), c.getEstadoLicencia()};
            tabla.addRow(fila);
        }
    }

    public void cargarTabla() {
        if (vistaInicial.ctrlconductor.validarArchivo() == true) {
            tabla.setNumRows(0);
            for (Conductor c : vistaInicial.ctrlconductor.cargarConductores()) {
                String[] fila = {c.getIdentificacion(), c.getNombre().toUpperCase(), c.getApellido().toUpperCase(), c.getTelefono(), c.getNroLicencia(), c.getEstadoLicencia()};
                tabla.addRow(fila);
                vistaInicial.ctrlconductor.agregar(c);
                vistaInicial.ctrlconductor.agregar(c);
            }
        }
    }

    public void mostrarConsulta() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
        }
        tabla.setNumRows(0);
        for (Conductor c : vistaInicial.ctrlconductor.getConductores()) {
            String[] fila = {c.getIdentificacion(), c.getNombre().toUpperCase(), c.getApellido().toUpperCase(), c.getTelefono(), c.getNroLicencia(), c.getEstadoLicencia()};
            tabla.addRow(fila);
            nombre.setText(c.getNombre());
            apellido.setText(c.getApellido());
            telefono.setText(c.getTelefono());
            nroLicencia.setText(c.getNroLicencia());
            nombre.setEnabled(true);
            apellido.setEnabled(true);
            jRadioButtonMas.setEnabled(true);
            jRadioButtonFem.setEnabled(true);
        }
    }

    public void mostrarConductorActualizar() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
        }
        tabla.setNumRows(0);
        for (Conductor c : vistaInicial.ctrlconductor.getConductores()) {
            String[] fila = {c.getIdentificacion(), c.getNombre().toUpperCase(), c.getApellido().toUpperCase(), c.getTelefono(), c.getNroLicencia(), c.getEstadoLicencia()};
            tabla.addRow(fila);
            nombre.setText(c.getNombre());
            apellido.setText(c.getApellido());
        }
    }

    public void vaciar() {
        identificacion.setText("");
        nombre.setText("");
        apellido.setText("");
        nroLicencia.setText("");
        telefono.setText("");
        buttonGroupSexo.clearSelection();
        buttonGroupEDL.clearSelection();
        Atras.setVisible(false);
        Añadir.setEnabled(true);
        Guardar.setEnabled(true);
        Modificar.setEnabled(true);
        jRadioButtonMas.setEnabled(true);
        jRadioButtonFem.setEnabled(true);
    }

    public String sexo() {
        String validar = "";
        if (jRadioButtonMas.isSelected()) {
            validar = "MASCULINO";
        }
        if (jRadioButtonFem.isSelected()) {
            validar = "FEMENINO";
        }
        return validar;
    }

    public String estadoDeLicencia() {
        String validar = "";
        if (jRadioButtonAct.isSelected()) {
            validar = "ACTIVO";
        }
        if (jRadioButtonInact.isSelected()) {
            validar = "INACTIVO";
        }
        return validar;
    }

    public void btnAñadir() {
        if (identificacion.getText().equals("") || nombre.getText().equals("")
                || apellido.getText().equals("") || nroLicencia.getText().equals("")
                || telefono.getText().equals("") || sexo().equals("")
                || estadoDeLicencia().equals("")) {

            JOptionPane.showMessageDialog(null, "¡FALTAN CAMPOS POR LLENAR!\n"
                    + "Por favor, complete todos los campos.", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (vistaInicial.ctrlconductor.verificarYAgregar(identificacion.getText()) == true) {
                JOptionPane.showMessageDialog(null, "Hay una persona con la misma identidicación, digite la correcta por favor.",
                        "Agregar conductor", JOptionPane.ERROR_MESSAGE);
                identificacion.setText("");
            } else {
                if (identificacion.getText().length() != 10 || nroLicencia.getText().length() != 8 || telefono.getText().length() != 10) {
                    JOptionPane.showMessageDialog(null, "Por favor, ingrese los digitos que se requieren en el campo IDENTIFICACIÓN, NUMERO DE LICENCIA o TELEFONO.", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    Conductor constructor = new Conductor();
                    constructor.setIdentificacion(identificacion.getText());
                    constructor.setNombre(nombre.getText());
                    constructor.setApellido(apellido.getText());
                    constructor.setSexo(sexo());
                    constructor.setEstadoLicencia(estadoDeLicencia());
                    constructor.setTelefono(telefono.getText());
                    constructor.setNroLicencia(nroLicencia.getText());
                    vistaInicial.ctrlconductor.agregar(constructor);
                    vaciar();
                    llenartabla();

                }
            }
        }
    }

    public void btnConsultar() {
        if (vistaInicial.ctrlconductor.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "No se ha registrado ningun conductor.", "Consultar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion del conductor a buscar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                vistaInicial.ctrlconductor.consultar(identificacion.getText());
                mostrarConsulta();
                Atras.setVisible(true);
                Añadir.setEnabled(false);
            }
        }
    }

    public void btnActualizar() {
        if (vistaInicial.ctrlconductor.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "La lista se encuentra vacía.", "Actualizar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion del conductor a actualizar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                mostrarConductorActualizar();
                nombre.setEnabled(false);
                apellido.setEnabled(false);
                jRadioButtonMas.setEnabled(false);
                jRadioButtonFem.setEnabled(false);
                if (telefono.getText().equals("") || nroLicencia.getText().equals("") || estadoDeLicencia().equals("")) {
                    JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos a actualizar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
                    Atras.setVisible(true);
                    Añadir.setEnabled(false);
                    Guardar.setEnabled(false);
                } else {
                    if (identificacion.getText().length() != 10 || nroLicencia.getText().length() != 8 || telefono.getText().length() != 10) {
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese los digitos que se requieren en el campo IDENTIFICACIÓN, NUMERO DE LICENCIA o TELEFONO.", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        vistaInicial.ctrlconductor.actualizar(identificacion.getText(), telefono.getText(), nroLicencia.getText(), estadoDeLicencia());
                        nombre.setEnabled(true);
                        apellido.setEnabled(true);
                        jRadioButtonMas.setEnabled(true);
                        jRadioButtonFem.setEnabled(true);
                        vaciar();
                        llenartabla();
                    }
                }
            }
        }
    }

    public void btnEliminar() {
        if (vistaInicial.ctrlconductor.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "La lista se encuentra vacía.", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion del conductor a eliminar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                boolean validar = vistaInicial.ctrlconductor.eliminar(identificacion.getText());
                if (validar == false) {
                    JOptionPane.showMessageDialog(null, "No existe algun conductor con esa identificación.", "Eliminar conductor", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    llenartabla();
                    vaciar();
                }
            }
        }
    }

    public void btnGuardar() {
        vistaInicial.ctrlconductor.guardarConductor();
    }

    public void btnAtras() {
        nombre.setEnabled(true);
        apellido.setEnabled(true);
        jRadioButtonMas.setEnabled(true);
        jRadioButtonFem.setEnabled(true);
        llenartabla();
        vaciar();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Añadir;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField apellido;
    private javax.swing.ButtonGroup buttonGroupEDL;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JTextField identificacion;
    private javax.swing.JRadioButton jRadioButtonAct;
    private javax.swing.JRadioButton jRadioButtonFem;
    private javax.swing.JRadioButton jRadioButtonInact;
    private javax.swing.JRadioButton jRadioButtonMas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nroLicencia;
    public java.awt.Panel panelOperaciones;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
