/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD_entidadesPrincipales;

import Modelo.Automovil;
import Modelo.Dueño;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Tous
 */
public class vistaAutomovil extends javax.swing.JFrame {

    /**
     * Creates new form vistaVehiculo
     */
    public vistaAutomovil() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        creartabla();
        cargarTabla();
        Atras.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOperaciones = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        Añadir = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        modelo = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        placa = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        dueño = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automovil");

        panelOperaciones.setBackground(new java.awt.Color(0, 66, 115));
        panelOperaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBackground(new java.awt.Color(14, 15, 34));

        jTable.setBackground(new java.awt.Color(184, 185, 194));
        jTable.setModel(tabla);
        jTable.setSelectionBackground(new java.awt.Color(55, 175, 177));
        jTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable);

        jlabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(240, 240, 240));
        jlabel1.setText("Dueño");

        jlabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(240, 240, 240));
        jlabel2.setText("Marca");

        jlabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(240, 240, 240));
        jlabel3.setText("Placa");

        jlabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(240, 240, 240));
        jlabel4.setText("Modelo");

        jlabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(240, 240, 240));
        jlabel5.setText("Color");

        Añadir.setBackground(new java.awt.Color(184, 185, 194));
        Añadir.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Añadir.setText("AÑADIR");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Consultar.setBackground(new java.awt.Color(184, 185, 194));
        Consultar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Consultar.setText("CONSULTAR");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(184, 185, 194));
        Modificar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Borrar.setBackground(new java.awt.Color(184, 185, 194));
        Borrar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Borrar.setText("BORRAR");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        modelo.setBackground(new java.awt.Color(184, 185, 194));
        modelo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        color.setBackground(new java.awt.Color(184, 185, 194));
        color.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        color.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        placa.setBackground(new java.awt.Color(184, 185, 194));
        placa.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placaKeyTyped(evt);
            }
        });

        marca.setBackground(new java.awt.Color(184, 185, 194));
        marca.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        dueño.setBackground(new java.awt.Color(184, 185, 194));
        dueño.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        dueño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dueño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dueñoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 9)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Ingrese la identificacion del propietario del vehiculo");

        Atras.setBackground(new java.awt.Color(184, 185, 194));
        Atras.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Atras.setText("ATRAS");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        Guardar.setBackground(new java.awt.Color(184, 185, 194));
        Guardar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperacionesLayout = new javax.swing.GroupLayout(panelOperaciones);
        panelOperaciones.setLayout(panelOperacionesLayout);
        panelOperacionesLayout.setHorizontalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlabel1)
                                .addComponent(jlabel2))
                            .addComponent(jlabel3)
                            .addComponent(jlabel4)
                            .addComponent(jlabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                                        .addComponent(Guardar)
                                        .addGap(18, 18, 18)
                                        .addComponent(Modificar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                                        .addComponent(Atras)
                                        .addGap(18, 18, 18)
                                        .addComponent(Borrar))
                                    .addComponent(Añadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Consultar))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addComponent(dueño, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        panelOperacionesLayout.setVerticalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel1)
                            .addComponent(dueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel3)))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel4)))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel5)
                    .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        btnEliminar();
    }//GEN-LAST:event_BorrarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        btnActualizar();
    }//GEN-LAST:event_ModificarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        btnConsultar();
    }//GEN-LAST:event_ConsultarActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        btnAñadir();
    }//GEN-LAST:event_AñadirActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        btnAtras();
    }//GEN-LAST:event_AtrasActionPerformed

    private void dueñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dueñoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (dueño.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_dueñoKeyTyped

    private void placaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placaKeyTyped
        if (placa.getText().length() >= 6) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_placaKeyTyped

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        btnGuardar();
    }//GEN-LAST:event_GuardarActionPerformed

    DefaultTableModel tabla = new DefaultTableModel();

    public void creartabla() {
        tabla.addColumn("PLACA");
        tabla.addColumn("MARCA");
        tabla.addColumn("MODELO");
        tabla.addColumn("COLOR");
        tabla.addColumn("DUEÑO");
    }

    public void llenartabla() {
        tabla.setNumRows(0);
        for (Automovil a : vistaInicial.ctrlauto.getAutos()) {
            String[] fila = {a.getPlaca().toUpperCase(), a.getMarca().toUpperCase(), a.getModeloVehiculo().toUpperCase(), a.getColor().toUpperCase(), a.getDueño().getNombre().toUpperCase() + " " + a.getDueño().getApellido().toUpperCase()};
            tabla.addRow(fila);
        }
    }

    public void cargarTabla() {
        if (vistaInicial.ctrlauto.validarArchivo() == true) {
            tabla.setNumRows(0);
            for (Automovil a : vistaInicial.ctrlauto.cargarAutos()) {
                String[] fila = {a.getPlaca().toUpperCase(), a.getMarca().toUpperCase(), a.getModeloVehiculo().toUpperCase(), a.getColor().toUpperCase(), a.getDueño().getNombre().toUpperCase() + " " + a.getDueño().getApellido().toUpperCase()};
                tabla.addRow(fila);
                vistaInicial.ctrlauto.agregar(a);
            }
        }
    }

    public void mostrarConsulta() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
        }
        tabla.setNumRows(0);
        for (Automovil a : vistaInicial.ctrlauto.getAutos()) {
            if (a.getPlaca().equalsIgnoreCase(placa.getText())) {
                String[] fila = {a.getPlaca().toUpperCase(), a.getMarca().toUpperCase(), a.getModeloVehiculo().toUpperCase(), a.getColor().toUpperCase(), a.getDueño().getNombre().toUpperCase() + " " + a.getDueño().getApellido().toUpperCase()};
                tabla.addRow(fila);
                dueño.setText(a.getDueño().getIdentificacion());
                marca.setText(a.getMarca());
                modelo.setText(a.getModeloVehiculo());
                color.setText(a.getColor());
                marca.setEnabled(true);
                modelo.setEnabled(true);
            }

        }
    }

    public void mostrarAutoActualizar() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
        }
        tabla.setNumRows(0);
        for (Automovil a : vistaInicial.ctrlauto.getAutos()) {
            if (a.getPlaca().equalsIgnoreCase(placa.getText())) {
                String[] fila = {a.getPlaca().toUpperCase(), a.getMarca().toUpperCase(), a.getModeloVehiculo().toUpperCase(), a.getColor().toUpperCase(), a.getDueño().getNombre().toUpperCase() + " " + a.getDueño().getApellido().toUpperCase()};
                tabla.addRow(fila);
                marca.setText(a.getMarca());
                modelo.setText(a.getModeloVehiculo());
            }

        }
    }

    public void vaciar() {
        dueño.setText("");
        marca.setText("");
        placa.setText("");
        modelo.setText("");
        color.setText("");
        Atras.setVisible(false);
        Añadir.setEnabled(true);
        Guardar.setEnabled(true);
        Modificar.setEnabled(true);
    }

    public boolean validarCampoPlaca() {
        String letras = placa.getText().substring(0, 3);
        String numeros = placa.getText().substring(3, 6);
        boolean validacion = true;

        for (int i = 0; i < letras.length(); i++) {
            if (!Character.isLetter(letras.charAt(i))) {
                validacion = false;
            }
        }

        for (int i = 0; i < numeros.length(); i++) {
            if (!Character.isDigit(numeros.charAt(i))) {
                validacion = false;
            }
        }
        return validacion;
    }

    public void btnAñadir() {
        if (placa.getText().equals("") || dueño.getText().equals("")
                || marca.getText().equals("") || modelo.getText().equals("")
                || color.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "¡FALTAN CAMPOS POR LLENAR!\n"
                    + "Por favor, complete todos los campos.", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (dueño.getText().length() != 10 || placa.getText().length() != 6) {
                JOptionPane.showMessageDialog(null, "Por favor, ingrese los caracteres que se requieren en el campo DUEÑO o PLACA", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (validarCampoPlaca() != true) {
                    JOptionPane.showMessageDialog(null, "Patron de placa incorrecto", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    if (vistaInicial.ctrlauto.verificarYAgregar(placa.getText()) == true) {
                        JOptionPane.showMessageDialog(null, "Hay un vehiculo con la misma placa, ingrese la placa correcta por favor.",
                                "Agregar", JOptionPane.ERROR_MESSAGE);
                        placa.setText("");
                    } else {
                        Modelo.Dueño dueñoAuto = vistaInicial.ctrldueño.asignarDueñoAuto(dueño.getText());
                        if (dueñoAuto != null) {
                            Automovil constructor = new Automovil();
                            constructor.setPlaca(placa.getText());
                            constructor.setDueño(dueñoAuto);
                            constructor.setMarca(marca.getText());
                            constructor.setModeloVehiculo(modelo.getText());
                            constructor.setColor(color.getText());
                            vistaInicial.ctrlauto.agregar(constructor);
                            vaciar();
                            llenartabla();
                        }
                    }
                }
            }
        }
    }

    public void btnConsultar() {
        if (vistaInicial.ctrlauto.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "No hay ningun vehiculo registrado.", "Consultar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (placa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la placa del vehiculo a buscar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                vistaInicial.ctrlauto.consultar(placa.getText());
                mostrarConsulta();
                Atras.setVisible(true);
                Añadir.setEnabled(false);
                Guardar.setEnabled(false);
                Modificar.setEnabled(false);
            }
        }
    }

    public void btnActualizar() {
        if (vistaInicial.ctrlauto.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "No hay ningun vehiculo registrado.", "Actualizar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (placa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la placa del vehiculo a actualizar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                mostrarAutoActualizar();
                marca.setEnabled(false);
                modelo.setEnabled(false);
                if (dueño.getText().equals("") || color.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
                    Atras.setVisible(true);
                    Añadir.setEnabled(false);
                    Guardar.setEnabled(false);
                } else {
                    if (dueño.getText().length() != 10 || placa.getText().length() != 6) {
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese los caracteres que se requieren en el campo DUEÑO o PLACA", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        Automovil automovil = vistaInicial.ctrlauto.actualizar(placa.getText(), dueño.getText(), color.getText());
                        if (automovil != null) {
                            marca.setEnabled(true);
                            modelo.setEnabled(true);
                            vaciar();
                            llenartabla();
                        }
                    }
                }
            }

        }
    }

    public void btnEliminar() {
        if (vistaInicial.ctrlauto.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "No hay ningun vehiculo registrado.", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (placa.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la placa del vehiculo a eliminar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                boolean validar = vistaInicial.ctrlauto.eliminar(placa.getText());
                if (validar == false) {
                    JOptionPane.showMessageDialog(null, "No existe algun vehiculo con esa placa", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    llenartabla();
                    vaciar();
                }
            }
        }
    }

    public void btnGuardar() {
        vistaInicial.ctrlauto.guardarAuto();
    }

    public void btnAtras() {
        marca.setEnabled(true);
        modelo.setEnabled(true);
        llenartabla();
        vaciar();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAutomovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Añadir;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField color;
    private javax.swing.JTextField dueño;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    public java.awt.Panel panelOperaciones;
    private javax.swing.JTextField placa;
    // End of variables declaration//GEN-END:variables
}
