/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD_entidadesPrincipales;

import Controlador.ControlDueño;
import Controlador.ControlAgente;
import Controlador.ControlConductor;
import Controlador.ControlAutomovil;
import Controlador.ControlResponsable;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Tous
 */
public class vistaInicial extends javax.swing.JFrame {

    /**
     * Creates new form vistaInicial
     */
    public vistaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        iniciarVentanas();
    }

    public void iniciarVentanas() {
        ventanaDueño.setVisible(false);
        ventanaAgenteDeTransito.setVisible(false);
        ventanaConductor.setVisible(false);
        ventanaAutomovil.setVisible(false);
        vistaDueño vdueño = new vistaDueño();
        ventanaDueño.add(vdueño.panelOperaciones);
        vistaAgenteDeTransito vagente = new vistaAgenteDeTransito();
        ventanaAgenteDeTransito.add(vagente.panelOperaciones);
        vistaConductor vconductor = new vistaConductor();
        ventanaConductor.add(vconductor.panelOperaciones);
        vistaAutomovil vauto = new vistaAutomovil();
        ventanaAutomovil.add(vauto.panelOperaciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnDueño = new javax.swing.JButton();
        btnAgenteDeTransito = new javax.swing.JButton();
        btnConductor = new javax.swing.JButton();
        btnAutomovil = new javax.swing.JButton();
        btnResponsable = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        ventanaDueño = new javax.swing.JInternalFrame();
        ventanaAutomovil = new javax.swing.JInternalFrame();
        ventanaAgenteDeTransito = new javax.swing.JInternalFrame();
        ventanaConductor = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de multas");

        jToolBar1.setBackground(new java.awt.Color(234, 234, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(127, 23));
        jToolBar1.setMinimumSize(new java.awt.Dimension(127, 23));
        jToolBar1.setPreferredSize(new java.awt.Dimension(127, 23));

        btnDueño.setBackground(new java.awt.Color(234, 234, 255));
        btnDueño.setText("Dueño");
        btnDueño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDueñoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDueño);

        btnAgenteDeTransito.setBackground(new java.awt.Color(234, 234, 255));
        btnAgenteDeTransito.setText("Agente de transito");
        btnAgenteDeTransito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenteDeTransitoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgenteDeTransito);

        btnConductor.setBackground(new java.awt.Color(234, 234, 255));
        btnConductor.setText("Conductor");
        btnConductor.setFocusable(false);
        btnConductor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConductor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConductorActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConductor);

        btnAutomovil.setBackground(new java.awt.Color(234, 234, 255));
        btnAutomovil.setText("Automoviles");
        btnAutomovil.setToolTipText("");
        btnAutomovil.setFocusable(false);
        btnAutomovil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAutomovil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomovilActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAutomovil);

        btnResponsable.setBackground(new java.awt.Color(234, 234, 255));
        btnResponsable.setText("Responsables");
        btnResponsable.setFocusable(false);
        btnResponsable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnResponsable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponsableActionPerformed(evt);
            }
        });
        jToolBar1.add(btnResponsable);

        jDesktopPane1.setBackground(new java.awt.Color(255, 235, 235));

        ventanaDueño.setClosable(true);
        ventanaDueño.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ventanaDueño.setIconifiable(true);
        ventanaDueño.setResizable(true);
        ventanaDueño.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        ventanaDueño.setVisible(true);

        javax.swing.GroupLayout ventanaDueñoLayout = new javax.swing.GroupLayout(ventanaDueño.getContentPane());
        ventanaDueño.getContentPane().setLayout(ventanaDueñoLayout);
        ventanaDueñoLayout.setHorizontalGroup(
            ventanaDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        ventanaDueñoLayout.setVerticalGroup(
            ventanaDueñoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );

        ventanaAutomovil.setClosable(true);
        ventanaAutomovil.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ventanaAutomovil.setIconifiable(true);
        ventanaAutomovil.setResizable(true);
        ventanaAutomovil.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        ventanaAutomovil.setVisible(true);

        javax.swing.GroupLayout ventanaAutomovilLayout = new javax.swing.GroupLayout(ventanaAutomovil.getContentPane());
        ventanaAutomovil.getContentPane().setLayout(ventanaAutomovilLayout);
        ventanaAutomovilLayout.setHorizontalGroup(
            ventanaAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );
        ventanaAutomovilLayout.setVerticalGroup(
            ventanaAutomovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        ventanaAgenteDeTransito.setClosable(true);
        ventanaAgenteDeTransito.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ventanaAgenteDeTransito.setIconifiable(true);
        ventanaAgenteDeTransito.setResizable(true);
        ventanaAgenteDeTransito.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        ventanaAgenteDeTransito.setVisible(true);

        javax.swing.GroupLayout ventanaAgenteDeTransitoLayout = new javax.swing.GroupLayout(ventanaAgenteDeTransito.getContentPane());
        ventanaAgenteDeTransito.getContentPane().setLayout(ventanaAgenteDeTransitoLayout);
        ventanaAgenteDeTransitoLayout.setHorizontalGroup(
            ventanaAgenteDeTransitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
        );
        ventanaAgenteDeTransitoLayout.setVerticalGroup(
            ventanaAgenteDeTransitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        ventanaConductor.setClosable(true);
        ventanaConductor.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ventanaConductor.setIconifiable(true);
        ventanaConductor.setResizable(true);
        ventanaConductor.setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));
        ventanaConductor.setVisible(true);

        javax.swing.GroupLayout ventanaConductorLayout = new javax.swing.GroupLayout(ventanaConductor.getContentPane());
        ventanaConductor.getContentPane().setLayout(ventanaConductorLayout);
        ventanaConductorLayout.setHorizontalGroup(
            ventanaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );
        ventanaConductorLayout.setVerticalGroup(
            ventanaConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(ventanaDueño, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ventanaAutomovil, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ventanaAgenteDeTransito, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ventanaConductor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(ventanaAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(ventanaDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ventanaAgenteDeTransito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(171, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(ventanaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(121, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ventanaAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addContainerGap(67, Short.MAX_VALUE)
                    .addComponent(ventanaDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(ventanaAgenteDeTransito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(ventanaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDueñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDueñoActionPerformed
        ventanaDueño.setVisible(true);
    }//GEN-LAST:event_btnDueñoActionPerformed

    private void btnAgenteDeTransitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenteDeTransitoActionPerformed
        ventanaAgenteDeTransito.setVisible(true);
    }//GEN-LAST:event_btnAgenteDeTransitoActionPerformed

    private void btnConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConductorActionPerformed
        ventanaConductor.setVisible(true);
    }//GEN-LAST:event_btnConductorActionPerformed

    private void btnAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomovilActionPerformed
        ventanaAutomovil.setVisible(true);
    }//GEN-LAST:event_btnAutomovilActionPerformed

    private void btnResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponsableActionPerformed
        vistaResponsable vresponsable = new vistaResponsable();
        vresponsable.setVisible(true);
    }//GEN-LAST:event_btnResponsableActionPerformed

    public static ControlDueño ctrldueño = new ControlDueño();
    public static ControlAgente ctrlagente = new ControlAgente();
    public static ControlConductor ctrlconductor = new ControlConductor();
    public static ControlAutomovil ctrlauto = new ControlAutomovil();
    public static ControlResponsable ctrlresponsable = new ControlResponsable();

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaInicial().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenteDeTransito;
    private javax.swing.JButton btnAutomovil;
    private javax.swing.JButton btnConductor;
    private javax.swing.JButton btnDueño;
    private javax.swing.JButton btnResponsable;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JInternalFrame ventanaAgenteDeTransito;
    private javax.swing.JInternalFrame ventanaAutomovil;
    private javax.swing.JInternalFrame ventanaConductor;
    private javax.swing.JInternalFrame ventanaDueño;
    // End of variables declaration//GEN-END:variables
}
