/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD_entidadesPrincipales;

import Modelo.AgenteDeTransito;
import Modelo.Automovil;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Tous
 */
public class vistaAgenteDeTransito extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public vistaAgenteDeTransito() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        creartabla();
        cargarTabla();
        Atras.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        panelOperaciones = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jlabel1 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        Añadir = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Borrar = new javax.swing.JButton();
        codigo = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        Atras = new javax.swing.JButton();
        identificacion = new javax.swing.JTextField();
        jlabel5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jlabel6 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jRadioButtonMas = new javax.swing.JRadioButton();
        jRadioButtonFem = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agente de transito");

        panelOperaciones.setBackground(new java.awt.Color(102, 46, 70));
        panelOperaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBackground(new java.awt.Color(14, 15, 34));

        jTable.setBackground(new java.awt.Color(184, 185, 194));
        jTable.setModel(tabla);
        jTable.setSelectionBackground(new java.awt.Color(55, 175, 177));
        jTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable);

        jlabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(184, 185, 194));
        jlabel1.setText("Nombre");

        jlabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(184, 185, 194));
        jlabel2.setText("Apellido");

        jlabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(184, 185, 194));
        jlabel3.setText("Codigo");

        jlabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(184, 185, 194));
        jlabel4.setText("Sexo");

        Añadir.setBackground(new java.awt.Color(184, 185, 194));
        Añadir.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Añadir.setText("AÑADIR");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });

        Consultar.setBackground(new java.awt.Color(184, 185, 194));
        Consultar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Consultar.setText("CONSULTAR");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(184, 185, 194));
        Modificar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Modificar.setText("MODIFICAR");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Borrar.setBackground(new java.awt.Color(184, 185, 194));
        Borrar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Borrar.setText("BORRAR");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        codigo.setBackground(new java.awt.Color(184, 185, 194));
        codigo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });

        apellido.setBackground(new java.awt.Color(184, 185, 194));
        apellido.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nombre.setBackground(new java.awt.Color(184, 185, 194));
        nombre.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Atras.setBackground(new java.awt.Color(184, 185, 194));
        Atras.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Atras.setText("ATRAS");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        identificacion.setBackground(new java.awt.Color(184, 185, 194));
        identificacion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        identificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        identificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                identificacionKeyTyped(evt);
            }
        });

        jlabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(184, 185, 194));
        jlabel5.setText("Identificación");

        email.setBackground(new java.awt.Color(184, 185, 194));
        email.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(184, 185, 194));
        jlabel6.setText("Email");

        Guardar.setBackground(new java.awt.Color(184, 185, 194));
        Guardar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        Guardar.setText("GUARDAR");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        jRadioButtonMas.setBackground(new java.awt.Color(102, 46, 70));
        buttonGroupSexo.add(jRadioButtonMas);
        jRadioButtonMas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButtonMas.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMas.setText("Masculino");
        jRadioButtonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonMasMouseClicked(evt);
            }
        });

        jRadioButtonFem.setBackground(new java.awt.Color(102, 46, 70));
        buttonGroupSexo.add(jRadioButtonFem);
        jRadioButtonFem.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jRadioButtonFem.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonFem.setText("Femenino");
        jRadioButtonFem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelOperacionesLayout = new javax.swing.GroupLayout(panelOperaciones);
        panelOperaciones.setLayout(panelOperacionesLayout);
        panelOperacionesLayout.setHorizontalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jlabel1)
                                        .addComponent(jlabel2))
                                    .addComponent(jlabel3)
                                    .addComponent(jlabel4)
                                    .addComponent(jlabel6))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                                .addComponent(jlabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(apellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(identificacion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addComponent(jRadioButtonMas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonFem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Modificar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Añadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Consultar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Borrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                                .addComponent(Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Atras)))
                        .addGap(51, 51, 51))))
        );
        panelOperacionesLayout.setVerticalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel5))
                        .addGap(18, 18, 18)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel1))
                        .addGap(18, 18, 18)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel2))
                        .addGap(24, 24, 24)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel4)
                            .addComponent(jRadioButtonMas)
                            .addComponent(jRadioButtonFem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(Añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlabel6))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        btnAtras();
    }//GEN-LAST:event_AtrasActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        btnEliminar();
    }//GEN-LAST:event_BorrarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        btnActualizar();
    }//GEN-LAST:event_ModificarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        btnConsultar();
    }//GEN-LAST:event_ConsultarActionPerformed

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        btnAñadir();
    }//GEN-LAST:event_AñadirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        btnGuardar();
    }//GEN-LAST:event_GuardarActionPerformed

    private void identificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_identificacionKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (identificacion.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_identificacionKeyTyped

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (codigo.getText().length() >= 3) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_codigoKeyTyped

    private void jRadioButtonMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonMasMouseClicked
        sexo();
    }//GEN-LAST:event_jRadioButtonMasMouseClicked

    private void jRadioButtonFemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFemMouseClicked
        sexo();
    }//GEN-LAST:event_jRadioButtonFemMouseClicked

    DefaultTableModel tabla = new DefaultTableModel();

    public void creartabla() {
        tabla.addColumn("CODIGO");
        tabla.addColumn("IDENTIFICACION");
        tabla.addColumn("NOMBRE");
        tabla.addColumn("APELLIDO");
        tabla.addColumn("SEXO");
        tabla.addColumn("ESTADO");
    }

    public void llenartabla() {
        tabla.setNumRows(0);
        for (AgenteDeTransito a : vistaInicial.ctrlagente.getAgentes()) {
                String[] fila = {a.getCodigo(), a.getIdentificacion(), a.getNombre().toUpperCase(), a.getApellido().toUpperCase(), a.getSexo(), a.getEstado()};
            tabla.addRow(fila);
        }
    }

    public void cargarTabla() {
        if (vistaInicial.ctrldueño.validarArchivo() == true) {
            tabla.setNumRows(0);
            for (AgenteDeTransito a : vistaInicial.ctrlagente.cargarAgentes()) {
                String[] fila = {a.getCodigo(), a.getIdentificacion(), a.getNombre().toUpperCase(), a.getApellido().toUpperCase(), a.getSexo(), a.getEstado()};
                tabla.addRow(fila);
                vistaInicial.ctrlagente.agregar(a);
            }
        }
    }

    public void mostrarConsulta() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
        }
        tabla.setNumRows(0);
        for (AgenteDeTransito a : vistaInicial.ctrlagente.getAgentes()) {
            if (a.getIdentificacion().equals(identificacion.getText())) {
                String[] fila = {a.getCodigo(), a.getIdentificacion(), a.getNombre().toUpperCase(), a.getApellido().toUpperCase(), a.getSexo(), a.getEstado()};
                tabla.addRow(fila);
                nombre.setText(a.getNombre());
                apellido.setText(a.getApellido());
                codigo.setText(a.getCodigo());
                email.setText(a.getEmail());
                nombre.setEnabled(true);
                apellido.setEnabled(true);
                jRadioButtonMas.setEnabled(true);
                jRadioButtonFem.setEnabled(true);
                identificacion.setEnabled(true);
            }
        }
    }

    public void mostrarAgenteActualizar() {
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
        }
        tabla.setNumRows(0);
        for (AgenteDeTransito a : vistaInicial.ctrlagente.getAgentes()) {
            if (a.getIdentificacion().equals(identificacion.getText())) {
                String[] fila = {a.getCodigo(), a.getIdentificacion(), a.getNombre().toUpperCase(), a.getApellido().toUpperCase(), a.getSexo(), a.getEstado()};
                tabla.addRow(fila);
                nombre.setText(a.getNombre());
                apellido.setText(a.getApellido());
            }
        }
    }

    public void vaciar() {
        identificacion.setText("");
        nombre.setText("");
        apellido.setText("");
        codigo.setText("");
        email.setText("");
        buttonGroupSexo.clearSelection();
        Atras.setVisible(false);
        Añadir.setEnabled(true);
        Guardar.setEnabled(true);
        Modificar.setEnabled(true);
    }

    public String sexo() {
        String validar = "";
        if (jRadioButtonMas.isSelected()) {
            validar = "MASCULINO";
        }
        if (jRadioButtonFem.isSelected()) {
            validar = "FEMENINO";
        }
        return validar;
    }

    public void btnAñadir() {
        if (identificacion.getText().equals("") || nombre.getText().equals("")
                || apellido.getText().equals("") || codigo.getText().equals("")
                || email.getText().equals("") || sexo().equals("")) {
            JOptionPane.showMessageDialog(null, "¡FALTAN CAMPOS POR LLENAR!\n"
                    + "Por favor, complete todos los campos.", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
        } else {
            if (vistaInicial.ctrlagente.verificarYAgregar(identificacion.getText()) == true) {
                JOptionPane.showMessageDialog(null, "Hay una persona con la misma identidicación, digite la correcta por favor.",
                        "Agregar agente", JOptionPane.ERROR_MESSAGE);
                identificacion.setText("");
            } else {
                if (identificacion.getText().length() != 10 || codigo.getText().length() != 3) {
                    JOptionPane.showMessageDialog(null, "Por favor, ingrese los digitos que se requieren en el campo IDENTIFICACION o CODIGO.", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    AgenteDeTransito constructor = new AgenteDeTransito();
                    constructor.setIdentificacion(identificacion.getText());
                    constructor.setNombre(nombre.getText());
                    constructor.setApellido(apellido.getText());
                    constructor.setSexo(sexo());
                    constructor.setCodigo(codigo.getText());
                    constructor.setEmail(email.getText());
                    constructor.setEstado("ACTIVO");
                    constructor.setUsuario(constructor.getIdentificacion());
                    constructor.setContraseña(constructor.getIdentificacion());
                    vistaInicial.ctrlagente.agregar(constructor);
                    vaciar();
                    llenartabla();
                }
            }
        }
    }

    public void btnConsultar() {
        if (vistaInicial.ctrlagente.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "No se ha registrado ningun agente.", "Consultar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion del agente a buscar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                vistaInicial.ctrlagente.consultar(identificacion.getText());
                mostrarConsulta();
                Atras.setVisible(true);
                Añadir.setEnabled(false);
                Guardar.setEnabled(false);
                Modificar.setEnabled(false);
            }
        }
    }

    public void btnActualizar() {
        if (vistaInicial.ctrlagente.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "No se ha registrado ningun agente.", "Actualizar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion del agente a actualizar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                mostrarAgenteActualizar();
                nombre.setEnabled(false);
                apellido.setEnabled(false);;
                jRadioButtonMas.setEnabled(false);
                jRadioButtonFem.setEnabled(false);
                if (email.getText().equals("") || codigo.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Por favor, complete los campos a actualizar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
                    Atras.setVisible(true);
                    Añadir.setEnabled(false);
                    Guardar.setEnabled(false);
                } else {
                    if (identificacion.getText().length() != 10 || codigo.getText().length() != 3) {
                        JOptionPane.showMessageDialog(null, "Por favor, ingrese los digitos que se requieren en el campo IDENTIFICACION o CODIGO.", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        vistaInicial.ctrlagente.actualizar(identificacion.getText(), email.getText(), codigo.getText());
                        nombre.setEnabled(true);
                        apellido.setEnabled(true);
                        jRadioButtonMas.setEnabled(true);
                        jRadioButtonFem.setEnabled(true);
                        vaciar();
                        llenartabla();
                    }
                }
            }

        }
    }

    public void btnEliminar() {
        if (vistaInicial.ctrlagente.listaVacia() == true) {
            JOptionPane.showMessageDialog(null, "La lista se encuentra vacía.", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (identificacion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese la identificacion del agente a eliminar", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
            } else {
                boolean validar = vistaInicial.ctrlagente.eliminar(identificacion.getText());
                if (validar == false) {
                    JOptionPane.showMessageDialog(null, "No existe algun agente con esa identificación.", "Eliminar agente", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    llenartabla();
                    vaciar();
                }
            }
        }
    }

    public void btnGuardar() {
        vistaInicial.ctrlagente.guardarAgente();
    }

    public void btnAtras() {
        nombre.setEnabled(true);
        apellido.setEnabled(true);
        jRadioButtonMas.setEnabled(true);
        jRadioButtonFem.setEnabled(true);
        llenartabla();
        vaciar();
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaAgenteDeTransito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Añadir;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField apellido;
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField email;
    private javax.swing.JTextField identificacion;
    private javax.swing.JRadioButton jRadioButtonFem;
    private javax.swing.JRadioButton jRadioButtonMas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JTextField nombre;
    public java.awt.Panel panelOperaciones;
    // End of variables declaration//GEN-END:variables
}
