/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasFuncionales;

import Controlador.ControlSancion;
import Modelo.Sancion;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Tous
 */
public class vistaCancelar extends javax.swing.JFrame {

    /**
     * Creates new form vistaCancelar
     */
    public vistaCancelar() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        rootPane.setDefaultButton(jButtonConfirmar);
        inhabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMetodoPago = new javax.swing.ButtonGroup();
        panelOperaciones = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        regresar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        identificacionUsuario = new javax.swing.JLabel();
        jlabel5 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        jlabel7 = new javax.swing.JLabel();
        jlabel8 = new javax.swing.JLabel();
        jlabel9 = new javax.swing.JLabel();
        jlabelagente = new javax.swing.JLabel();
        jlabelpersona = new javax.swing.JLabel();
        jlabelfecha = new javax.swing.JLabel();
        jlabelhora = new javax.swing.JLabel();
        jlabellugar = new javax.swing.JLabel();
        multa = new javax.swing.JLabel();
        jlabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jlabel11 = new javax.swing.JLabel();
        fechaVencimiento = new javax.swing.JLabel();
        jlabel12 = new javax.swing.JLabel();
        tipoInfraccion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonE = new javax.swing.JRadioButton();
        jRadioButtonL = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        codigo_enLnea = new javax.swing.JTextField();
        jButtonEnter = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxTarjetas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelOperaciones.setBackground(new java.awt.Color(102, 0, 51));
        panelOperaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CANCELAR MULTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(325, 325, 325))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        regresar.setBackground(new java.awt.Color(184, 185, 194));
        regresar.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        regresar.setText("REGRESAR");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(regresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        identificacionUsuario.setFont(new java.awt.Font("Calibri", 2, 12)); // NOI18N
        identificacionUsuario.setForeground(new java.awt.Color(255, 255, 255));
        identificacionUsuario.setText("IDENTIFICACION");
        identificacionUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(identificacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(identificacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jlabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(184, 185, 194));
        jlabel5.setText("AGENTE QUE IMPUSO LA INFRACCIÓN:");

        jlabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(184, 185, 194));
        jlabel6.setText("PERSONA QUE REALIZA LA ALEGACIÓN:");

        jlabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabel7.setForeground(new java.awt.Color(184, 185, 194));
        jlabel7.setText("LUGAR DE LA INFRACCIÓN:");

        jlabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabel8.setForeground(new java.awt.Color(184, 185, 194));
        jlabel8.setText("FECHA DE LA INFRACCIÓN:");

        jlabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabel9.setForeground(new java.awt.Color(184, 185, 194));
        jlabel9.setText("HORA DE LA INFRACCIÓN:");

        jlabelagente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabelagente.setForeground(new java.awt.Color(184, 185, 194));

        jlabelpersona.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabelpersona.setForeground(new java.awt.Color(184, 185, 194));

        jlabelfecha.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabelfecha.setForeground(new java.awt.Color(184, 185, 194));

        jlabelhora.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabelhora.setForeground(new java.awt.Color(184, 185, 194));

        jlabellugar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jlabellugar.setForeground(new java.awt.Color(184, 185, 194));

        multa.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        multa.setForeground(new java.awt.Color(184, 185, 194));

        jlabel10.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jlabel10.setForeground(new java.awt.Color(184, 185, 194));
        jlabel10.setText("VALOR MULTA:");

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jlabel11.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jlabel11.setForeground(new java.awt.Color(184, 185, 194));
        jlabel11.setText("PAGAR HASTA:");

        fechaVencimiento.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        fechaVencimiento.setForeground(new java.awt.Color(184, 185, 194));

        jlabel12.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jlabel12.setForeground(new java.awt.Color(184, 185, 194));
        jlabel12.setText("TIPO DE INFRACCIÓN:");

        tipoInfraccion.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        tipoInfraccion.setForeground(new java.awt.Color(184, 185, 194));

        jPanel2.setBackground(new java.awt.Color(102, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(184, 185, 194));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione el metodo de pago");

        jRadioButtonE.setBackground(new java.awt.Color(102, 0, 51));
        buttonGroupMetodoPago.add(jRadioButtonE);
        jRadioButtonE.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jRadioButtonE.setForeground(new java.awt.Color(184, 185, 194));
        jRadioButtonE.setText("EFECTIVO");
        jRadioButtonE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonEMouseClicked(evt);
            }
        });

        jRadioButtonL.setBackground(new java.awt.Color(102, 0, 51));
        buttonGroupMetodoPago.add(jRadioButtonL);
        jRadioButtonL.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jRadioButtonL.setForeground(new java.awt.Color(184, 185, 194));
        jRadioButtonL.setText("EN LÍNEA");
        jRadioButtonL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jRadioButtonE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jRadioButtonL)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonE)
                    .addComponent(jRadioButtonL))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(102, 0, 51));

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(184, 185, 194));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText(" ");

        codigo_enLnea.setBackground(new java.awt.Color(184, 185, 194));
        codigo_enLnea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigo_enLnea.setForeground(new java.awt.Color(0, 0, 0));
        codigo_enLnea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigo_enLneaKeyTyped(evt);
            }
        });

        jButtonEnter.setBackground(new java.awt.Color(184, 185, 194));
        jButtonEnter.setFont(new java.awt.Font("Rockwell", 3, 12)); // NOI18N
        jButtonEnter.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEnter.setText("ENTER");
        jButtonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(184, 185, 194));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(" ");

        jLabel13.setFont(new java.awt.Font("Rockwell", 2, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(184, 185, 194));
        jLabel13.setText("¡El pago se ha realizado exitosamente!");

        jComboBoxTarjetas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBoxTarjetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "BANCOLOMBIA", "DAVIVIENDA", "BBVA COLOMBIA", "BANCO POPULAR", "BANCO AV VILLAS" }));

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(184, 185, 194));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText(" ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigo_enLnea, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 152, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEnter)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(23, 23, 23))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTarjetas)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_enLnea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jButtonEnter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(31, 31, 31))
        );

        jButtonConfirmar.setBackground(new java.awt.Color(74, 0, 51));
        jButtonConfirmar.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButtonConfirmar.setForeground(new java.awt.Color(184, 185, 194));
        jButtonConfirmar.setText("CONFIRMAR");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOperacionesLayout = new javax.swing.GroupLayout(panelOperaciones);
        panelOperaciones.setLayout(panelOperacionesLayout);
        panelOperacionesLayout.setHorizontalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabel6)
                            .addComponent(jlabel8)
                            .addComponent(jlabel9)
                            .addComponent(jlabel7)
                            .addComponent(jlabel10)
                            .addComponent(jlabel11)
                            .addComponent(jlabel5)
                            .addComponent(jlabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlabelhora, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jlabellugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabelagente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabelpersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabelfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaVencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoInfraccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelOperacionesLayout.setVerticalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jlabelagente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOperacionesLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabelpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel8)
                                    .addComponent(jlabelfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel9)
                                    .addComponent(jlabelhora, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel7)
                                    .addComponent(jlabellugar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipoInfraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonConfirmar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(15, 15, 15))
                            .addGroup(panelOperacionesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(panelOperacionesLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        sancion = null;
        vistaCivil.seleccion = false;
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        btnConfirmar();
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jRadioButtonLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonLMouseClicked
        metodoPago();
    }//GEN-LAST:event_jRadioButtonLMouseClicked

    private void jRadioButtonEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonEMouseClicked
        metodoPago();
    }//GEN-LAST:event_jRadioButtonEMouseClicked

    private void jButtonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterActionPerformed
        btnEnter();
    }//GEN-LAST:event_jButtonEnterActionPerformed

    private void codigo_enLneaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigo_enLneaKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(null, "Ingrese solo valores numericos", "Tipo de dato incompatible", JOptionPane.INFORMATION_MESSAGE);
        }

        if (codigo_enLnea.getText().length() >= 16) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_codigo_enLneaKeyTyped

    void inhabilitar() {
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jComboBoxTarjetas.setVisible(false);
        codigo_enLnea.setEnabled(false);
        jButtonEnter.setEnabled(false);
        jButtonConfirmar.setEnabled(false);
    }

    void Activar() {
        jLabel10.setVisible(true);
        jLabel12.setVisible(true);
        codigo_enLnea.setEnabled(true);
        jButtonEnter.setEnabled(true);
    }

    void btnConfirmar() {
        JOptionPane.showMessageDialog(null, "¡DATOS CONFIRMADOS!", "CONFIRMAR DATOS", JOptionPane.INFORMATION_MESSAGE);
        Activar();
        jButtonConfirmar.setEnabled(false);
        if (metodoPago().equals("efectivo")) {
            jButtonEnter.setVisible(false);
            JOptionPane.showMessageDialog(null, "Se ha generado un codigo de 6 digitos con el cual puede cancelar la infracción en algun punto de pago.", "CANCELAR PAGO", JOptionPane.INFORMATION_MESSAGE);
            ctrlSancion.cancelarSancion(sancion.getDetalleDeInfraccion().getInfraccion().getResponsable().getVehiculo().getDueño().getIdentificacion());
            sancion = null;
            vistaCivil.seleccion = false;
            vistaCivil.jButtonActualizar.setVisible(true);
            vistaCivil.sanciones.clear();
        } else {
            jLabel11.setVisible(true);
            jComboBoxTarjetas.setVisible(true);
        }
    }

    void btnEnter() {
        if (jComboBoxTarjetas.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, seleccione con que tarjeta desea cancelar.", "CANCELAR PAGO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (codigo_enLnea.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese su numero de cuenta", "CANCELAR PAGO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (codigo_enLnea.getText().length() != 16) {
                    JOptionPane.showMessageDialog(null, "Ingrese su numero correcto de cuenta", "CANCELAR PAGO", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    int num = JOptionPane.showConfirmDialog(null, "¿Autoriza el pago?", "CANCELAR PAGO", JOptionPane.YES_NO_OPTION);
                    if (num == 0) {
                        jLabel13.setVisible(true);
                        codigo_enLnea.setEnabled(false);
                        jButtonEnter.setEnabled(false);
                        ctrlSancion.cancelarSancion(sancion.getDetalleDeInfraccion().getInfraccion().getResponsable().getVehiculo().getDueño().getIdentificacion());
                        sancion = null;
                        vistaCivil.seleccion = false;
                        vistaCivil.jButtonActualizar.setVisible(true);
                        vistaCivil.sanciones.clear();
                    }
                }
            }
        }
    }

    String metodoPago() {
        String valor = "";
        if (jRadioButtonE.isSelected()) {
            String codigo = "" + (int) ((1000000) * Math.random());
            valor = "efectivo";
            jLabel12.setText("CONFIRMACÍON DE PAGO EN EFECTIVO");
            jLabel10.setText("Codigo generado");
            codigo_enLnea.setText(codigo);
            codigo_enLnea.setEditable(false);
            jButtonConfirmar.setEnabled(true);
        }
        if (jRadioButtonL.isSelected()) {
            valor = "en linea";
            jLabel12.setText("CONFIRMACÍON DE PAGO EN LINEA");
            jLabel11.setText("Seleccione la tarjeta");
            jLabel10.setText("Ingrese nro de cuenta");
            codigo_enLnea.setText("");
            codigo_enLnea.setEditable(true);
            jButtonConfirmar.setEnabled(true);
        }
        return valor;
    }

    ControlSancion ctrlSancion = new ControlSancion();
    public static Sancion sancion = null;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCancelar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCancelar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupMetodoPago;
    private javax.swing.JTextField codigo_enLnea;
    public static javax.swing.JLabel fechaVencimiento;
    public static javax.swing.JLabel identificacionUsuario;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JComboBox<String> jComboBoxTarjetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonE;
    private javax.swing.JRadioButton jRadioButtonL;
    private javax.swing.JLabel jlabel10;
    private javax.swing.JLabel jlabel11;
    private javax.swing.JLabel jlabel12;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel jlabel9;
    public static javax.swing.JLabel jlabelagente;
    public static javax.swing.JLabel jlabelfecha;
    public static javax.swing.JLabel jlabelhora;
    public static javax.swing.JLabel jlabellugar;
    public static javax.swing.JLabel jlabelpersona;
    public static javax.swing.JLabel multa;
    public java.awt.Panel panelOperaciones;
    private javax.swing.JButton regresar;
    public static javax.swing.JLabel tipoInfraccion;
    // End of variables declaration//GEN-END:variables
}
